f = open("task5.txt", 'w', encoding='utf-8')
f.write(input('Введите набор чисел, разделяя их пробелами: '))
f.close()
f = open("task5.txt", encoding='utf-8')
line = f.readline()
line = list(map(int, line.split()))
res = sum(line)
f.close()
print(res)